
module.exports = [
 {quote:`I have seen many storms in my life. Most storms have caught me by surprise, so I had to learn very quickly to look further and understand that I am not capable of controlling the weather, to exercise the art of patience and to respect the fury of nature.`},
 {quote:`When you are enthusiastic about what you do, you feel this positive energy. It's very simple.`},
 {quote:`Life was always a matter of waiting for the right moment to act.`},
 {quote:`No one can lie, no one can hide anything, when he looks directly into someone's eyes.`},
 {quote:`Be brave. Take risks. Nothing can substitute experience.`},
 {quote:`Culture makes people understand each other better. And if they understand each other better in their soul, it is easier to overcome the economic and political barriers. But first they have to understand that their neighbour is, in the end, just like them, with the same problems, the same questions.`},
 {quote:`What I can say is that all my characters are searching for their souls, because they are my mirrors. I'm someone who is constantly trying to understand my place in the world, and literature is the best way that I found in order to see myself.`},
 {quote:`You drown not by falling into a river, but by staying submerged in it.`},
 {quote:`I write from my soul. This is the reason that critics don't hurt me, because it is me. If it was not me, if I was pretending to be someone else, then this could unbalance my world, but I know who I am.`},
 {quote:`I can control my destiny, but not my fate. Destiny means there are opportunities to turn right or left, but fate is a one-way street. I believe we all have the choice as to whether we fulfil our destiny, but our fate is sealed.`},
 {quote:`When you want something, all the universe conspires in helping you to achieve it.`},
 {quote:`I cry very easily. It can be a movie, a phone conversation, a sunset - tears are words waiting to be written.`},
 {quote:`One is loved because one is loved. No reason is needed for loving.`},
 {quote:`Physical elegance, which is what I am talking about here, comes from the body. This is no superficial matter, but rather the way that man found to honour the way he places his two feet on the ground.`},
 {quote:`Love is a trap. When it appears, we see only its light, not its shadows.`},
 {quote:`Remember your dreams and fight for them. You must know what you want from life. There is just one thing that makes your dream become impossible: the fear of failure.`},
 {quote:`When a person really desires something, all the universe conspires to help that person to realize his dream.`},
 {quote:`You have to take risks. We will only understand the miracle of life fully when we allow the unexpected to happen.`},
 {quote:`Let us be absolutely clear about one thing: we must not confuse humility with false modesty or servility.`},
 {quote:`Every day I try to be in communication with the universe in an unconscious way.`},
 {quote:`The wise are wise only because they love. The fool are fools only because they think they can understand love.`},
 {quote:`It's very difficult to read a book on your computer.`},
 {quote:`Every blessing ignored becomes a curse.`},
 {quote:`Everything that happens once can never happen again. But everything that happens twice will surely happen a third time.`},
 {quote:`I walk every day, and I look at the mountains and the fields and the small city, and I say: 'Oh my God, what a blessing.' Then you realise it's important to put it in a context beyond this woman, this man, this city, this country, this universe.`},
 {quote:`There is an afterlife. I am convinced of this.`},
 {quote:`It took me 40 years to write my first book. When I was a child, I was encouraged to go to school. I was not encouraged to follow the career of a writer because my parents thought that I was going to starve to death.`},
 {quote:`Tell your heart that the fear of suffering is worse than the suffering itself. And no heart has ever suffered when it goes in search of its dream.`},
 {quote:`No, I never saw an angel, but it is irrelevant whether I saw one or not. I feel their presence around me.`},
 {quote:`You're always learning. The problem is, sometimes you stop and think you understand the world. This is not correct. The world is always moving. You never reach the point you can stop making an effort.`},
]